"""Add BountyApplication table

Revision ID: 07749dfa9dbe
Revises: 963ec99e0e08
Create Date: 2021-03-05 16:46:54.693554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07749dfa9dbe'
down_revision = '963ec99e0e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounty_application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('application_text', sa.String(), nullable=True),
    sa.Column('bounty_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounty.bounty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bounty_application')
    # ### end Alembic commands ###
