"""Add completed column to bounty table

Revision ID: 0aa3bb3a6f4e
Revises: 282fdaaa2938
Create Date: 2021-04-17 12:44:49.398115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa3bb3a6f4e'
down_revision = '282fdaaa2938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounty', 'completed')
    # ### end Alembic commands ###
