"""Add submission columns to bounty table

Revision ID: 131a7b618cfe
Revises: 0aa3bb3a6f4e
Create Date: 2021-04-19 14:39:11.529760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131a7b618cfe'
down_revision = '0aa3bb3a6f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('is_submit', sa.Boolean(), nullable=True))
    op.add_column('bounty', sa.Column('submission_description', sa.String(length=1000), nullable=True))
    op.add_column('bounty', sa.Column('submission_link', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_bounty_submission_link'), 'bounty', ['submission_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bounty_submission_link'), 'bounty', type_='unique')
    op.drop_column('bounty', 'submission_link')
    op.drop_column('bounty', 'submission_description')
    op.drop_column('bounty', 'is_submit')
    # ### end Alembic commands ###
