"""Add github_access_token column to user table

Revision ID: 4524b64aef6b
Revises: e6d3f05db4a2
Create Date: 2021-04-22 15:25:24.653079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4524b64aef6b'
down_revision = 'e6d3f05db4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_access_token', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_github_access_token'), 'user', ['github_access_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_github_access_token'), 'user', type_='unique')
    op.drop_column('user', 'github_access_token')
    # ### end Alembic commands ###
