"""Add url column to Bounty table

Revision ID: 7f70f68cde00
Revises: 07749dfa9dbe
Create Date: 2021-03-08 14:49:26.652179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f70f68cde00'
down_revision = '07749dfa9dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'bounty', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bounty', type_='unique')
    op.drop_column('bounty', 'url')
    # ### end Alembic commands ###
