"""add amount column to bounty and investment table

Revision ID: 929da93b0fd7
Revises: 3a6e925954e8
Create Date: 2021-03-19 20:59:16.234260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929da93b0fd7'
down_revision = '3a6e925954e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('amount', sa.BigInteger(), nullable=False))
    op.add_column('investment', sa.Column('amount', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment', 'amount')
    op.drop_column('bounty', 'amount')
    # ### end Alembic commands ###
