"""Add submission datetime to bounty table

Revision ID: af19943b7bf2
Revises: 131a7b618cfe
Create Date: 2021-04-19 14:55:36.980836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af19943b7bf2'
down_revision = '131a7b618cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('submission_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounty', 'submission_datetime')
    # ### end Alembic commands ###
