"""Add bounty submission approval table

Revision ID: c7dac1919229
Revises: af19943b7bf2
Create Date: 2021-04-19 18:35:33.486815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dac1919229'
down_revision = 'af19943b7bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounty_submission_approval',
    sa.Column('bounty_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('decision_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounty.bounty_id'], name=op.f('fk_bounty_submission_approval_bounty_id_bounty'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_bounty_submission_approval_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bounty_id', 'user_id', name=op.f('pk_bounty_submission_approval'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bounty_submission_approval')
    # ### end Alembic commands ###
