"""Add completion date row to bounty table

Revision ID: d102e90aa4cb
Revises: c7dac1919229
Create Date: 2021-04-20 16:18:41.486106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd102e90aa4cb'
down_revision = 'c7dac1919229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('completion_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounty', 'completion_datetime')
    # ### end Alembic commands ###
