"""Remove unique constraint from submission_link column in bounty table

Revision ID: e6d3f05db4a2
Revises: d102e90aa4cb
Create Date: 2021-04-20 19:47:24.485480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d3f05db4a2'
down_revision = 'd102e90aa4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bounty_submission_link', 'bounty', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bounty_submission_link', 'bounty', ['submission_link'])
    # ### end Alembic commands ###
